version: 2.1

executors:
  default:
    docker:
      - image: cimg/base:2024.01

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run: echo "Building the project"

  deploy:
    executor: default
    steps:
      - checkout
      - run: |
          echo "Deploying to AWS ECS"
          # Add your AWS CLI commands here to deploy to ECS

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build