version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.05
    steps:
      - checkout
      - run: echo "Building the accounting project"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build